routingPanier:
    resource: "@EcommerceSiteBundle/Resources/config/routing/routingPanier.yml"
    prefix:   /panier

routingProduits:
    resource: "@EcommerceSiteBundle/Resources/config/routing/routingProduits.yml"
    prefix:   /

routingCommande:
    resource: "@EcommerceSiteBundle/Resources/config/routing/routingCommandes.yml"
    prefix:   /