ecommerce_site_panier_homepage:
    path:     /panier
    defaults: { _controller: EcommerceSiteBundle:Panier:panier }

ecommerce_site_panier_livraison:
    path:     /panier/livraison
    defaults: { _controller: EcommerceSiteBundle:Panier:livraison }

ecommerce_site_panier_validation:
    path:     /panier/validation
    defaults: { _controller: EcommerceSiteBundle:Panier:validation }

ecommerce_site_produits_homepage:
    path:     /
    defaults: { _controller: EcommerceSiteBundle:Produits:produits }

ecommerce_site_prod_presentation:
    path:     /prod
    defaults: { _controller: EcommerceSiteBundle:Produits:presentation }
