services:
#    ecommerce_site.example:
#        class: EcommerceSite\EcommerceSiteBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    tva:
        class: EcommerceSite\EcommerceSiteBundle\Twig\Extensions\TvaExtension
        tags:
          - { name: twig.extension }

    montantTva:
        class: EcommerceSite\EcommerceSiteBundle\Twig\Extensions\MontantTvaExtension
        tags:
          - { name: twig.extension }

    redirectionListener:
        class: EcommerceSite\EcommerceSiteBundle\Listener\RedirectionListener
        arguments: [@service_container, @session]
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    setNewReference:
        class: EcommerceSite\EcommerceSiteBundle\Services\GetLatestReference
        arguments: [@security.token_storage, @doctrine.orm.entity_manager]
