services:
#    ecommerce_site.example:
#        class: EcommerceSite\EcommerceSiteBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    tva:
        class: EcommerceSite\EcommerceSiteBundle\Twig\Extensions\TvaExtension
        tags:
          - { name: twig.extension }

