ecommerce:
    resource: "@EcommerceBundle/Resources/config/routing.yml"
    prefix:   /ecom

utilisateurs:
   resource: "@UtilisateursBundle/Resources/config/routing.yml"
   prefix:   /

pages:
    resource: "@PagesBundle/Resources/config/routing.yml"
    prefix:   /

ecommerce_site:
    resource: "@EcommerceSiteBundle/Resources/config/routing.yml"
    prefix:   /

